version: 2.1
executors:
  my_executor:
    docker:
      - image: circleci/openjdk:8

jobs:
  digdag:
    executor: my_executor
    steps:
      - checkout
      - run:
          name: Setup
          command: |
              mkdir -p ~/bin/
              curl -o ~/bin/digdag -L "https://dl.digdag.io/digdag-latest"
              chmod +x ~/bin/digdag
              echo 'export PATH="$HOME/bin:$PATH"' >> $BASH_ENV

      - run:
          name: Push project
          command: cd unification_test && digdag check && digdag push unification_test -e https://api-workflow.treasuredata.com -X client.http.headers.authorization="TD1 $TD_API_KEY" -r `date -u +"%Y-%m-%dT%H:%M:%SZ"`-`git rev-parse HEAD`

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - digdag
      # If you would like to restrict branches/tags to running Digdag jobs, use `filters` option.
      # Following filter means `digdag` job will run only `dev` and `user-` starting branches.
      # @see: https://circleci.com/docs/2.0/workflows/
      #  - digdag:
      #      filters:
      #        branches:
      #          only:
      #            - dev
      #            - /user-.*/